version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates every weekday
      interval: "daily"
