name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test with code coverage
        run: yarn coverage
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage/lcov.info
          env_vars: CI_OS,NODE_VERSION
        env:
          CI_OS: ${{ matrix.os }}
          NODE_VERSION: ${{ matrix.node-version }}

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
